apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domino-workflow-shared-storage-volume-claim
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
